### ISSUE TITLE
Add graphql file

### ISSUE THREAD

**Issue by RichardLitt** [RichardLitt/jabbar#2]

**Comment by millette** [comment]
Like https://github.com/RichardLitt/jabbar/blob/master/queries/watchers.query.yaml ?

I was wondering why they were wrapped in yaml too.

**Comment by RichardLitt** [comment]
Yes, but more like actual queries which are run. The yaml file is a format for storing GraphQL queries as a file themselves. I'm going to look into how to integrate them formally this morning.

**Comment by millette** [comment]
Replace the hardcoded values with graphql variables and you should be good to go :-)

**Comment by RichardLitt** [comment]
Pretty much. Got this figure out, for now. Closing. :)
