### ISSUE TITLE
Figure out pagination

### ISSUE THREAD

**Issue by RichardLitt** [RichardLitt/jabbar#9]

**Comment by millette** [comment]
You might want to have a look at [ghraphql](https://github.com/millette/ghraphql) which I use everyday to update <http://dev.rollodeqc.com/>.

**Comment by RichardLitt** [comment]
Kind of went with a custom solution. It works, for now. I couldn't figure out how to grok your code, in particular the throttler. Any advice would be great. :)

**Comment by millette** [comment]
I don't think the rate limiter is as useful as a year ago. Queries had different costs, etc. I should simplify ghraphql one of these days.

For pagination, you need to fetch `pageInfo` in your GraphQL as in <https://github.com/millette/ghraphql/blob/6d45d04a904e914a70d8b7901fc66ccd1a5ba896/query.graphql#L12>

Then, basically loop your query (async) until `search.pageInfo.hasNextPage` is false.

**Comment by RichardLitt** [comment]
In that case, I think I am doing it right? The only weird thing is how to abstract it beyond the child relationship.
